
INSERT  INTO  PAYMENT_METHOD(NAME,DISCOUNT_AVAILABLE) VALUES('UPI','5.0');

INSERT  INTO  PAYMENT(AMOUNT, TRANSACTION_DATE, TRANSACTION_ID,PAYMENT_METHOD_ID,HAS_ORDER) VALUES('100','12-04-2021, 14:00','TR120', '1',false );